In [1]:
import numpy as np

In [2]:
_y_score_zero = np.array((1.0, 1.5, 1.3))

In [3]:
_y_score_zero.shape

(3,)

In [4]:
_y_score_one = np.array((1.6, 1.9, 2.2, 0.3))

In [5]:
_y_score_one.shape

(4,)

In [6]:
_y_label_zero = np.zeros(_y_score_zero.shape[0])

In [7]:
_y_label_one = np.ones(_y_score_one.shape[0])

In [8]:
_y_label_zero.shape

(3,)

In [9]:
_y_label_one.shape

(4,)

In [10]:
np.concatenate([_y_score_zero, _y_score_one], axis=0)

array([ 1. ,  1.5,  1.3,  1.6,  1.9,  2.2,  0.3])

In [11]:
np.concatenate([_y_label_zero, _y_label_one], axis=0)

array([ 0.,  0.,  0.,  1.,  1.,  1.,  1.])

In [12]:
y_true = np.concatenate([_y_label_zero, _y_label_one], axis=0)
y_score = np.concatenate([_y_score_zero, _y_score_one], axis=0)

In [13]:
from sklearn.metrics import roc_curve
from sklearn.metrics import auc

In [14]:
fpr, tpr, _ = roc_curve(y_true, y_score)

In [15]:
auc_value = auc(fpr, tpr)

In [16]:
fpr, tpr

(array([ 0.,  0.,  1.,  1.]), array([ 0.25,  0.75,  0.75,  1.  ]))

In [17]:
auc_value

0.75